name: test_git_suraj
description: test git fork
version: v.01
author: suraj.thakur@cloudaeon.net
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: testgitsuraj
  parentArtefactID: surajthakurcloudaeonnetteam
  buildSystem: wheel
  author: null
  createdAt: '2024-03-13 08:07:59'
pipelines:
  pipelines/first_pipeline:
    name: first_pipeline
    description: ''
    author: suraj.thakur@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-03-13 08:07:59'
    datasets:
      inputs:
      - datasets/first_dataset
      outputs:
      - datasets/target_dataset
    subgraphs: []
    dependencies: {}
datasets:
  datasets/first_dataset:
    name: first_dataset
    description: ''
    author: suraj.thakur@cloudaeon.net
    createdAt: '2024-03-13 08:09:23'
    mode: batch
    physicalDatasets:
      suraj_dev:
        fabricId: 10146
        datasetType: File
        description: ''
        author: suraj.thakur@cloudaeon.net
        createdAt: '2024-03-13 08:09:23'
  datasets/target_dataset:
    name: target_dataset
    description: ''
    author: suraj.thakur@cloudaeon.net
    createdAt: '2024-03-13 08:11:20'
    mode: batch
    physicalDatasets:
      suraj_dev:
        fabricId: 10146
        datasetType: File
        description: ''
        author: suraj.thakur@cloudaeon.net
        createdAt: '2024-03-13 08:11:20'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-03-13 08:07:59'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.4
    isDefault: true
    author: null
    createdAt: '2024-03-13 08:05:54'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.3
    isDefault: true
    author: null
    createdAt: '2024-03-13 08:05:54'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
